"""Compatibility shim for ``d810.hexrays.hexrays_helpers``.

The canonical implementation lives in :mod:`d810.hexrays.utils.hexrays_helpers`.
This module re-exports its public surface so external scripts, tests,
and persisted plugin code that import the legacy path keep working.

Do not add new logic here. New code must import from
``d810.hexrays.utils.hexrays_helpers`` directly.
"""
from __future__ import annotations

from d810.hexrays.utils.hexrays_helpers import (  # noqa: F401
    AND_TABLE,
    ARITHMETICAL_OPCODES,
    BIT_OPERATIONS_OPCODES,
    BOOLEAN_OPCODES,
    CHECK_OPCODES,
    CONDITIONAL_JUMP_OPCODES,
    CONTROL_FLOW_OPCODES,
    CachedOpcodeInfo,
    MBA_RELATED_OPCODES,
    MINSN_TO_AST_FORBIDDEN_OPCODES,
    MOP_TYPE_TO_STRING_DICT,
    MSB_TABLE,
    MATURITY_TO_STRING_DICT,
    MicroInstruction,
    MicroOperand,
    MicrocodeHelper,
    MicrocodeOpcode,
    MaturityLevel,
    OPCODES_INFO,
    OperandType,
    OpcodeInfo,
    STRING_TO_MATURITY_DICT,
    SUB_TABLE,
    UNCONDITIONAL_JUMP_OPCODES,
    Z3_SPECIAL_OPERANDS,
    analyze_instruction_enhanced,
    analyze_operand_enhanced,
    append_mop_if_not_in_list,
    check_ins_have_same_operands,
    check_ins_mop_size_are_ok,
    check_mop_is_result_of,
    create_constant_operand,
    create_instruction,
    create_instruction_from_internal,
    create_operand_from_internal,
    create_register_operand,
    dup_mop,
    equal_bnot_cst,
    equal_bnot_mop,
    equal_ignore_msb_cst,
    equal_mops_bypass_xdu,
    equal_mops_ignore_size,
    extract_by_opcode_type,
    extract_literal_from_mop,
    extract_num_mop,
    get_blk_index,
    get_mop_index,
    get_opcode_info,
    is_check_mop,
    is_rotate_helper_call,
    mop_quick_key_ignore_size,
    structural_mop_hash,
)

__all__ = [
    "AND_TABLE",
    "ARITHMETICAL_OPCODES",
    "BIT_OPERATIONS_OPCODES",
    "BOOLEAN_OPCODES",
    "CHECK_OPCODES",
    "CONDITIONAL_JUMP_OPCODES",
    "CONTROL_FLOW_OPCODES",
    "CachedOpcodeInfo",
    "MBA_RELATED_OPCODES",
    "MINSN_TO_AST_FORBIDDEN_OPCODES",
    "MOP_TYPE_TO_STRING_DICT",
    "MSB_TABLE",
    "MATURITY_TO_STRING_DICT",
    "MicroInstruction",
    "MicroOperand",
    "MicrocodeHelper",
    "MicrocodeOpcode",
    "MaturityLevel",
    "OPCODES_INFO",
    "OperandType",
    "OpcodeInfo",
    "STRING_TO_MATURITY_DICT",
    "SUB_TABLE",
    "UNCONDITIONAL_JUMP_OPCODES",
    "Z3_SPECIAL_OPERANDS",
    "analyze_instruction_enhanced",
    "analyze_operand_enhanced",
    "append_mop_if_not_in_list",
    "check_ins_have_same_operands",
    "check_ins_mop_size_are_ok",
    "check_mop_is_result_of",
    "create_constant_operand",
    "create_instruction",
    "create_instruction_from_internal",
    "create_operand_from_internal",
    "create_register_operand",
    "dup_mop",
    "equal_bnot_cst",
    "equal_bnot_mop",
    "equal_ignore_msb_cst",
    "equal_mops_bypass_xdu",
    "equal_mops_ignore_size",
    "extract_by_opcode_type",
    "extract_literal_from_mop",
    "extract_num_mop",
    "get_blk_index",
    "get_mop_index",
    "get_opcode_info",
    "is_check_mop",
    "is_rotate_helper_call",
    "mop_quick_key_ignore_size",
    "structural_mop_hash",
]